config/routes.rb
Rails.application.routes.draw do
  resources :teams
  resources :scores
  resources :playdays do
    collection do
      get 'ranking'
    end
  end
  resources :sessions, only: [:index] do
    collection do
      post "login"
    end
  end
  #resources :requests
  #resources :cup_stats
  #resources :rp_tickets do
    #collection do
      #post 'receive'
    #end
  #end
  #resources :static_pages, only: [:index], path: "" do
    #collection do
      #get 'statistics'
      #get 'data'
      #get 'history'
      #get 'cups'
      #get 'rp'
      #post 'rps'
      #get 'eslm'
      #post 'cup'
    #end
  #end
  root 'teams#index'
end

app/models/playday.rb
class Playday < ActiveRecord::Base
  has_many :scores
end

app/controllers/playdays_controller.rb
class PlaydaysController < ApplicationController
    layout 'pubg_eslm_layout'
    skip_before_action :verify_authenticity_token, only: [:create]
    before_action :checkSession, only: [:index, :new]
    
    def index
    
    
    end

    def show
        checkSession
        @Playday = Playday.find(params[:id])
    end


    def new
        
    end

    def ranking
        @ranking = {}
        Team.all.each do |t|
            @ranking[t.id] = {k: 0, p: 0}
        end
        scores = Score.all
        scores.each do |s|
            id = s.team_id
            k = s.kills
            p = s.points
            puts 490/100*50
            pro = Playday.find(s.playday_id).prozent
            p = p * (pro * 0.01)
            h_k = @ranking[id][:k]
            h_p = @ranking[id][:p]
            #puts "#{id} #{h_k} #{h_p}"
            @ranking[id] = {k: k + h_k, p: p + h_p}
        end
        @ranking = @ranking.sort do |a,b|
            b[1][:p] <=> a[1][:p]
        end
        puts @ranking
    end

    def create
        playday = Playday.create(number: params[:nummer], division: params[:division], prozent: params[:prozent])
        teams = Team.where(division: params[:division])
        teams.each do |t|
            playday.scores << t.scores.create(kills: 0, points: 0)
        end
        redirect_to playdays_path
    end
end

app/views/playdays/index.html.haml
- playdays = Playday.all
.container-fluid
  .row
    %h1 Alle Spieltage
  .row.justify-content-center
    .col-8
      - playdays.each do |playday|
        .row
          %a{href: "#{playday_path(playday)}"}
            = "Spieltag #{playday.number} #{playday.division}"

app/views/playdays/new.html.haml
.container-fluid.justify-content-center
  .row
    .col-8
      %h1 Neuen Spieltag erstellen
  .row
    .col-8
      .row
        .col-2
          Spieltag Nr.
        .col-6
          = text_field_tag "nummer"
      .row
        .col-2
          Division
        .col-6
          = text_field_tag "division"
      .row
        .col-2
          Prozent
        .col-6
          = number_field_tag "prozent"
      .row
        %button.btn#save
          Save
- content_for :javascript do
  :javascript
    let url = "#{playdays_path}"
    $('#save').click(function(){
      $.ajax(url,{
        method: "POST",
        data: {
          nummer: $('#nummer').val(),
          division: $('#division').val(),
          prozent: $('#prozent').val()
        }
      }).done(function(data) {
        alert("Spieltag erstellt!");
      })
    });

app/views/playdays/ranking.html.haml
- rank = 1
.mvp
  %table.ranking{"cellspacing": 0}
    %tr{style: "border-bottom: 1px solid"}
      %th
        Platz
      %th
        Team
      %th
        Kills
      %th
        Total
    - @ranking.each do |r|
      - team = Team.find(r[0])
      - kills = r[1][:k]
      - points = r[1][:p]
      - color = "#000"
      - if team.division == "Elite"
        - color = "#842727"
      - elsif team.division == "Diamond"
        - color = "#4147f4"
      %tr.mvpitem
        %td{style: "text-align: center"}
          = rank
        %td{style: "color: #{color}; font-weight: bolder"}
          = team.name
        %td{style: "text-align: center"}
          = kills
        %td{style: "text-align: center"}
          = points.round
          - rank += 1

app/views/playdays/show.html.haml
%h1
    = "Spieltag #{@Playday.number} #{@Playday.division}"
- count = 0
%table.table
    %tr
        %th
            Name
        %th
            Kills
        %th
            Points
    - @Playday.scores.each do |score|
        %tr
            %td
                = "#{score.team.name}"
            %td
                %input.kills{type: "number", value: score.kills,style: "width: 50px", "kill_score_id": score.id, "count_k": count}
            %td
                %input.points{type: "number", value: score.points,style: "width: 50px", "points_score_id": score.id, "count_p": count}
            - count += 1
%button.btn#save
    Save
- content_for :javascript do
    :javascript
        let url = "#{scores_path}"
        let ids = [];
        $('#save').click(function(){
            $('.kills').each(function(e,b){
                let kills = $('.kills')[e].value;
                let points = $('.points')[e].value;
                let id = $('.kills')[e].attributes[2].value
                ids.push({id: id, kills: kills, points: points});
            })
            $.ajax(url,{    
                method: "POST",
                data: {
                    data: ids
                }
            }).done(function(data) {
                location.reload(); 
                ids = [];
            })
        });